[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "non-avian-ml-toy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
run = "./run_prod_workflow.sh"

[dependencies]
python = "3.10.*"
libgl = "*"
glib = "*"
pixi-kernel = ">=0.6.2,<0.7"
pip = ">=25.0.1,<26"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.3.6,<5"

[pypi-dependencies] 
tensorflow = "==2.14.0"
tensorflow_hub = "*"
opensoundscape = ">=0.11.0"
torch = "*"
numpy = "*"
pandas = ">=2.2.3, <3"
tqdm = "*"
timm = "*"
torchaudio = "*"
executing = "*"
scikit-learn = ">=1.6.1, <2"
bioacoustics-model-zoo = { git = "git+https://github.com/kitzeslab/bioacoustics-model-zoo" }
